# Stage 1, based on Nginx, to have only the compiled app, ready for production with Nginx
FROM nginx:1.14
COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf

## Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*

## From ‘builder’ stage copy over the artifacts in dist folder to default nginx public folder
COPY dist/nginx-site /usr/share/nginx/html

RUN chmod -R 777  /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
